name: "Create issue from a PR"
description: "This action helps open source devs in the track of new PRs"
inputs:
  repo:
    description: 'Repository name'
    required: true
  token:
    description: 'Github token'
    required: true
  org:
    description: 'Organization name'
    required: true
  title:
    description: 'Issue title'
    required: true
  body:
    description: 'Issue body'
    required: true
  user:
    description: 'User that made the PR'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
